name: Update RSS Feed

on:
  schedule:
    - cron: "0 * * * *"  # Jede Stunde
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run RSS generator
        run: python generate_rss.py
      - name: Commit & push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/rss.xml
          git commit -m "Update RSS Feed" || echo "No changes"
          git push
